### ISSUE TITLE
[BUG]  Agent mode does not work on PyCharm 2026.1

### ISSUE THREAD

**Issue by aleksejs-fomins** [devoxx/DevoxxGenieIDEAPlugin#1100]
## Bug Description

Agent mode does not work on PyCharm 2026.1 using llama3.3 model from Ollama on Ubuntu Linux. Ask mode works fine.

## Steps to Reproduce

1. Curl latest Ollama
2. Install and run the llama3.3 model
3. Install devoxxGenie plugin on pycharm
4. Toggle agent mode, ask any question

## Expected Behavior

Get agentic behaviour

## Actual Behavior

Get crash

## Screenshots/Logs

15:30:18.946 [prompt-exec-4] ERROR c.d.g.s.prompt.error.PromptException - ERROR:Error occurred while processing chat message - false
15:30:18.946 [prompt-exec-4] ERROR c.d.g.s.p.error.PromptErrorHandler - Error occurred while processing chat message
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/intellij/psi/PsiModifierListOwner
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1791)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/PsiModifierListOwner
	at com.devoxx.genie.service.agent.tool.BuiltInToolProvider.registerPsiTools(BuiltInToolProvider.java:416)
	at com.devoxx.genie.service.agent.tool.BuiltInToolProvider.<init>(BuiltInToolProvider.java:205)
	at com.devoxx.genie.service.agent.AgentToolProviderFactory.createToolProvider(AgentToolProviderFactory.java:59)
	at com.devoxx.genie.service.prompt.response.nonstreaming.NonStreamingPromptExecutionService.processChatMessage(NonStreamingPromptExecutionService.java:215)
	at com.devoxx.genie.service.prompt.response.nonstreaming.NonStreamingPromptExecutionService.lambda$executeQuery$0(NonStreamingPromptExecutionService.java:83)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1789)

## Environment

- **PyCharm Version**: 2026.1
- **Plugin Version**: 1.7.4
- **Operating System**: Ubuntu 22.04
- **LLM Provider**: Ollama
- **Model**: llama3.3

**Comment by aleksejs-fomins** [comment]
According to Gemini, plugin attempts to use Java Program Structure Interface which is available in IDEA but not available in PyCharm

**Comment by stephanj** [comment]
Have you tried turning off the PSI feature in the Agent Mode settings page?

<img width="983" height="695" alt="Image" src="https://github.com/user-attachments/assets/fd4544d9-2d42-440d-945b-1bf1c349c3f2" />

**Comment by aleksejs-fomins** [comment]
> Have you tried turning off the PSI feature in the Agent Mode settings page?
> <img alt="Image" width="983" height="695" src="https://private-user-images.githubusercontent.com/179457/605880718-fd4544d9-2d42-440d-945b-1bf1c349c3f2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODExMDc0NzEsIm5iZiI6MTc4MTEwNzE3MSwicGF0aCI6Ii8xNzk0NTcvNjA1ODgwNzE4LWZkNDU0NGQ5LTJkNDItNDQwZC05NDViLTFiZjFjMzQ5YzNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYxMFQxNTU5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzM5NjBlNzNjODE4YjEyM2QwMjgwZjJmNDY2ZDVlODg5ZDE1YjMwOTRhZmJmMDljYzNjNGVjNWExNWI1ZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Oza_tPgkAmuJmdq2By9rWQYlAF5-Y7CZZrYlZEdYV64">

Nope, just tried now, and I get a new bug

18:01:17.927 [prompt-exec-2] ERROR c.d.g.s.p.r.n.NonStreamingPromptExecutionService - {"error":"registry.ollama.ai/library/llama3:latest does not support tools"}
18:01:17.927 [prompt-exec-2] ERROR c.d.g.s.prompt.error.PromptException - ERROR:Provider unavailable: {"error":"registry.ollama.ai/library/llama3:latest does not support tools"} - true
18:01:17.927 [prompt-exec-2] ERROR c.d.g.s.prompt.error.PromptException - ERROR:Error occurred while processing chat message - false
18:01:17.927 [prompt-exec-2] ERROR c.d.g.s.p.error.PromptErrorHandler - Error occurred while processing chat message
java.util.concurrent.CompletionException: com.devoxx.genie.service.prompt.error.ModelException: Provider unavailable: {"error":"registry.ollama.ai/library/llama3:latest does not support tools"}
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1791)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: com.devoxx.genie.service.prompt.error.ModelException: Provider unavailable: {"error":"registry.ollama.ai/library/llama3:latest does not support tools"}
	at com.devoxx.genie.service.prompt.response.nonstreaming.NonStreamingPromptExecutionService.processChatMessage(NonStreamingPromptExecutionService.java:261)
	at com.devoxx.genie.service.prompt.response.nonstreaming.NonStreamingPromptExecutionService.lambda$executeQuery$0(NonStreamingPromptExecutionService.java:83)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1789)
	... 3 common frames omitted
Caused by: dev.langchain4j.exception.InvalidRequestException: {"error":"registry.ollama.ai/library/llama3:latest does not support tools"}
	at dev.langchain4j.internal.ExceptionMapper$DefaultExceptionMapper.mapHttpStatusCode(ExceptionMapper.java:71)
	at dev.langchain4j.internal.ExceptionMapper$DefaultExceptionMapper.mapException(ExceptionMapper.java:44)
	at dev.langchain4j.internal.ExceptionMapper.withExceptionMapper(ExceptionMapper.java:31)
	at dev.langchain4j.internal.RetryUtils.lambda$withRetryMappingExceptions$1(RetryUtils.java:326)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:204)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:263)
	at dev.langchain4j.internal.RetryUtils.withRetryMappingExceptions(RetryUtils.java:326)
	at dev.langchain4j.internal.RetryUtils.withRetryMappingExceptions(RetryUtils.java:309)
	at dev.langchain4j.model.ollama.OllamaChatModel.doChat(OllamaChatModel.java:41)
	at dev.langchain4j.model.chat.ChatModel.chat(ChatModel.java:61)
	at dev.langchain4j.model.chat.ChatModel.chat(ChatModel.java:36)
	at dev.langchain4j.guardrail.SynchronousChatExecutor.execute(SynchronousChatExecutor.java:32)
	at dev.langchain4j.guardrail.AbstractChatExecutor.executeInternal(AbstractChatExecutor.java:66)
	at dev.langchain4j.guardrail.AbstractChatExecutor.execute(AbstractChatExecutor.java:52)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:333)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:162)
	at com.devoxx.genie.service.prompt.response.nonstreaming.$Proxy253.chat(Unknown Source)
	at com.devoxx.genie.service.prompt.response.nonstreaming.NonStreamingPromptExecutionService.processChatMessage(NonStreamingPromptExecutionService.java:238)
	... 5 common frames omitted
Caused by: dev.langchain4j.exception.HttpException: {"error":"registry.ollama.ai/library/llama3:latest does not support tools"}
	at dev.langchain4j.http.client.jdk.JdkHttpClient.execute(JdkHttpClient.java:54)
	at dev.langchain4j.model.ollama.OllamaClient.chat(OllamaClient.java:116)
	at dev.langchain4j.model.ollama.OllamaChatModel.lambda$doChat$0(OllamaChatModel.java:41)
	at dev.langchain4j.internal.ExceptionMapper.withExceptionMapper(ExceptionMapper.java:29)
	... 20 common frames omitted

**Comment by stephanj** [comment]
This is because llama3.3 doesn't support tools, you need to select a language model with tool support like Gemma4, GML-4.7-flash, Qwen 3.5, 3.6 etc.  

Ollama tags these with "tools" 

<img width="1018" height="533" alt="Image" src="https://github.com/user-attachments/assets/1f0d228d-0650-4c27-8b5a-03e2a08313f4" />

**Comment by stephanj** [comment]
BTW You can download v1.8.1 which will disable PSI when you're using a none-Java-enabled JetBrains IDE like PyCharm etc.

https://github.com/devoxx/DevoxxGenieIDEAPlugin/releases/tag/v1.8.1

**Comment by aleksejs-fomins** [comment]
Wow you are fast. Thanks for your advice!
